[build]
  command = "jekyll build --config _config.yml"
[context.preview] # 'preview' is the branch name
  command = "jekyll build --config _config.yml,_config-preview.yml"
[context.11ty] # '11ty' is the branch name
  command = "eleventy"
